$(document).ready(function () {
  var board = Board(),
      canvas = document.getElementById('canvas'),
      context = canvas.getContext("2d"),
      whitePawn1   = Piece('white-pawn', board.positions.A2),
      whitePawn2   = Piece('white-pawn', board.positions.B2),
      whitePawn3   = Piece('white-pawn', board.positions.C2),
      whitePawn4   = Piece('white-pawn', board.positions.D2),
      whitePawn5   = Piece('white-pawn', board.positions.E2),
      whitePawn6   = Piece('white-pawn', board.positions.F2),
      whitePawn7   = Piece('white-pawn', board.positions.G2),
      whitePawn8   = Piece('white-pawn', board.positions.H2),
      whiteBishop1 = Piece('white-bishop', board.positions.C1),
      whiteBishop2 = Piece('white-bishop', board.positions.F1),
      whiteKnight1 = Piece('white-knight', board.positions.B1),
      whiteKnight2 = Piece('white-knight', board.positions.G1),
      whiteTower1  = Piece('white-tower', board.positions.A1),
      whiteTower2  = Piece('white-tower', board.positions.H1),
      whiteKing    = Piece('white-king', board.positions.E1),
      whiteQueen   = Piece('white-queen', board.positions.D1),
      blackPawn1   = Piece('black-pawn', board.positions.A7),
      blackPawn2   = Piece('black-pawn', board.positions.B7),
      blackPawn3   = Piece('black-pawn', board.positions.C7),
      blackPawn4   = Piece('black-pawn', board.positions.D7),
      blackPawn5   = Piece('black-pawn', board.positions.E7),
      blackPawn6   = Piece('black-pawn', board.positions.F7),
      blackPawn7   = Piece('black-pawn', board.positions.G7),
      blackPawn8   = Piece('black-pawn', board.positions.H7),
      blackBishop1 = Piece('black-bishop', board.positions.C8),
      blackBishop2 = Piece('black-bishop', board.positions.F8),
      blackKnight1 = Piece('black-knight', board.positions.B8),
      blackKnight2 = Piece('black-knight', board.positions.G8),
      blackTower1  = Piece('black-tower', board.positions.A8),
      blackTower2  = Piece('black-tower', board.positions.H8),
      blackKing    = Piece('black-king', board.positions.E8),
      blackQueen   = Piece('black-queen', board.positions.D8)

  var pieces = [
    whitePawn1,
    whitePawn2,
    whitePawn3,
    whitePawn4,
    whitePawn5,
    whitePawn6,
    whitePawn7,
    whitePawn8,
    whiteBishop1,
    whiteBishop2,
    whiteKnight1,
    whiteKnight2,
    whiteTower1,
    whiteTower2,
    whiteKing,
    whiteQueen,
    blackPawn1,
    blackPawn2,
    blackPawn3,
    blackPawn4,
    blackPawn5,
    blackPawn6,
    blackPawn7,
    blackPawn8,
    blackBishop1,
    blackBishop2,
    blackKnight1,
    blackKnight2,
    blackTower1,
    blackTower2,
    blackKing,
    blackQueen
  ]

  board.init(context, pieces)
  canvas.addEventListener("mousedown", board.click, false)
})